# -*- coding: utf-8 -*-
"""Babydog.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gG_U8SadQNoW_PJd3uATlvVGMggPktD9
"""

!pip install diffusers transformers accelerate torch Pillow -q

import torch
from diffusers import StableDiffusionPipeline
from PIL import Image, ImageDraw, ImageFont
import os
import json
from IPython.display import display

DOG_CONFIG = {
    "dog_breed": "corgi",
    "dog_color": "red",
    "trainer": "adult woman",
    "reward_item": "bone treat",
    "environment": "sunny grass field outdoors",
}

NEGATIVE_PROMPT = (
    "blurry, deformed, extra limbs, bad anatomy, low quality, "
    "cartoon, anime, painting, indoor, watermark, text, ugly"
)

BASELINE_PROMPT = "a dog training tutorial, educational scene"

N_RUNS = 5

PANEL_TEMPLATES = {
    1: (
        "A {dog_color} {dog_breed} dog and an {trainer} standing together "
        "on a {environment}, with a frisbee and a {reward_item} visible, "
        "preparing for fetch training. Realistic photo, natural light."
    ),
    2: (
        "An {trainer} throwing a frisbee across a {environment}, "
        "a {dog_color} {dog_breed} dog watching eagerly in the distance. "
        "Fetch dog training tutorial scene. Realistic photo."
    ),
    3: (
        "A {dog_color} {dog_breed} dog running back across a {environment} "
        "with a frisbee in its mouth, looking happy. "
        "Fetch dog training tutorial scene. Realistic photo."
    ),
    4: (
        "An {trainer} kneeling down giving a {reward_item} to a {dog_color} {dog_breed} dog "
        "on a {environment}, the dog sitting obediently. "
        "Positive reinforcement dog training. Realistic photo."
    ),
}

PANEL_LABELS = {
    1: "Panel 1: Setup",
    2: "Panel 2: Throw",
    3: "Panel 3: Fetch",
    4: "Panel 4: Reward",
}

def build_structured_prompts(config):
    return {
        panel_id: template.format(**config)
        for panel_id, template in PANEL_TEMPLATES.items()
    }

structured_prompts = build_structured_prompts(DOG_CONFIG)
baseline_prompts = {i: BASELINE_PROMPT for i in range(1, 5)}

print("=== Structured Prompts ===")
for pid, p in structured_prompts.items():
    print(f"\nPanel {pid}: {p}")

print("\n=== Baseline Prompt ===")
print(BASELINE_PROMPT)

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
)
pipe = pipe.to("cuda")
pipe.enable_attention_slicing()
print("Model loaded.")

def generate_image(pipe, prompt, negative_prompt, seed):
    generator = torch.Generator("cuda").manual_seed(seed)
    result = pipe(
        prompt=prompt,
        negative_prompt=negative_prompt,
        num_inference_steps=30,
        guidance_scale=7.5,
        width=512,
        height=512,
        generator=generator,
    )
    return result.images[0]

def make_grid(images, labels, title):
    """Create a 1-row image grid with title and panel labels"""
    W, H = 512, 512
    label_h = 36
    title_h = 48
    padding = 12
    cols = len(images)

    total_w = W * cols + padding * (cols + 1)
    total_h = title_h + label_h + H + padding * 2

    grid = Image.new("RGB", (total_w, total_h), (245, 245, 245))
    draw = ImageDraw.Draw(grid)

    # Draw title
    draw.text((total_w // 2, title_h // 2), title,
              fill=(30, 30, 30), anchor="mm")

    for i, (img, label) in enumerate(zip(images, labels)):
        x = padding + i * (W + padding)
        y = title_h + label_h

        # Draw panel label
        draw.text((x + W // 2, title_h + label_h // 2), label,
                  fill=(80, 80, 80), anchor="mm")

        grid.paste(img, (x, y))

    return grid

def run_experiment(pipe, prompts, negative_prompt, n_runs, exp_name):
    os.makedirs(f"/content/outputs/{exp_name}/grids", exist_ok=True)
    os.makedirs(f"/content/outputs/{exp_name}/panels", exist_ok=True)

    all_results = {}

    for run_id in range(n_runs):
        print(f"\n[{exp_name}] Run {run_id + 1}/{n_runs}")
        panels = {}
        images = []

        for panel_id in range(1, 5):
            seed = (run_id + 1) * 100 + panel_id
            print(f"  Generating Panel {panel_id} (seed={seed})...")
            img = generate_image(pipe, prompts[panel_id], negative_prompt, seed)

            path = f"/content/outputs/{exp_name}/panels/run{run_id+1}_panel{panel_id}.png"
            img.save(path)
            panels[panel_id] = img
            images.append(img)

        # Create 4-panel grid image
        title = f"{exp_name.upper()} — Run {run_id + 1}"
        labels = [PANEL_LABELS[i] for i in range(1, 5)]
        grid = make_grid(images, labels, title)
        grid_path = f"/content/outputs/{exp_name}/grids/run{run_id+1}_grid.png"
        grid.save(grid_path)

        all_results[run_id + 1] = panels
        print(f"  Grid saved: {grid_path}")

        # Display in Colab
        display(grid)

    return all_results

print("=" * 50)
print("EXPERIMENT A: Structured Prompts")
print("=" * 50)

results_structured = run_experiment(
    pipe=pipe,
    prompts=structured_prompts,
    negative_prompt=NEGATIVE_PROMPT,
    n_runs=N_RUNS,
    exp_name="structured",
)

print("=" * 50)
print("EXPERIMENT B: Baseline Prompt")
print("=" * 50)

results_baseline = run_experiment(
    pipe=pipe,
    prompts=baseline_prompts,
    negative_prompt=NEGATIVE_PROMPT,
    n_runs=N_RUNS,
    exp_name="baseline",
)

import csv

def create_scoring_sheet():
    os.makedirs("/content/outputs/scoring", exist_ok=True)

    # Part 1: Single-panel accuracy
    with open("/content/outputs/scoring/part1_single_panel.csv", "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([
            "run", "experiment", "panel",
            "dog_color_correct",        # Is the dog color correct? (0/1)
            "dog_breed_correct",        # Does the breed resemble a corgi? (0/1)
            "scene_correct",            # Is the environment correct (grass/outdoor)? (0/1)
            "prop_present",             # Is the required object present? (0/1)
            "action_correct",           # Is the action correct? (0/1)
            "single_score",             # Sum of the above (to be calculated)
            "notes",                    # Failure case description
        ])
        for run_id in range(1, N_RUNS + 1):
            for exp in ["structured", "baseline"]:
                for panel in range(1, 5):
                    writer.writerow([run_id, exp, panel, "", "", "", "", "", "", ""])

    # Part 2: Cross-panel consistency
    with open("/content/outputs/scoring/part2_cross_panel.csv", "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([
            "run", "experiment",
            "dog_color_consistent",         # Is the dog color consistent across panels? (0/1)
            "dog_appearance_consistent",    # Does it look like the same dog? (0/1)
            "scene_consistent",             # Is the environment consistent? (0/1)
            "story_coherent",               # Is the story progression coherent? (0/1)
            "props_continuous",             # Are props used correctly across panels? (0/1)
            "cross_score",                  # Sum (to be calculated)
            "notes",
        ])
        for run_id in range(1, N_RUNS + 1):
            for exp in ["structured", "baseline"]:
                writer.writerow([run_id, exp, "", "", "", "", "", "", ""])

    print("Scoring sheets generated:")
    print("  /content/outputs/scoring/part1_single_panel.csv")
    print("  /content/outputs/scoring/part2_cross_panel.csv")

create_scoring_sheet()

import pandas as pd

def summarize_scores():
    df1 = pd.read_csv("/content/outputs/scoring/part1_single_panel.csv")
    df2 = pd.read_csv("/content/outputs/scoring/part2_cross_panel.csv")

    score_cols1 = [
        "dog_color_correct",
        "dog_breed_correct",
        "scene_correct",
        "prop_present",
        "action_correct"
    ]

    score_cols2 = [
        "dog_color_consistent",
        "dog_appearance_consistent",
        "scene_consistent",
        "story_coherent",
        "props_continuous"
    ]

    # Convert to numeric
    df1[score_cols1] = df1[score_cols1].apply(pd.to_numeric, errors="coerce")
    df2[score_cols2] = df2[score_cols2].apply(pd.to_numeric, errors="coerce")

    # Compute scores
    df1["single_score"] = df1[score_cols1].sum(axis=1)
    df2["cross_score"] = df2[score_cols2].sum(axis=1)

    print("=" * 50)
    print("Part 1: Single-Panel Accuracy (Max Score = 5)")
    print("=" * 50)

    summary1 = df1.groupby("experiment")["single_score"].agg(["mean", "std"]).round(2)
    print(summary1)

    print("\nDetailed Metrics:")
    detail1 = df1.groupby("experiment")[score_cols1].mean().round(2)
    print(detail1)

    print("\n" + "=" * 50)
    print("Part 2: Cross-Panel Consistency (Max Score = 5)")
    print("=" * 50)

    summary2 = df2.groupby("experiment")["cross_score"].agg(["mean", "std"]).round(2)
    print(summary2)

    print("\nDetailed Metrics:")
    detail2 = df2.groupby("experiment")[score_cols2].mean().round(2)
    print(detail2)

    # Save summaries
    summary1.to_csv("/content/outputs/scoring/summary_part1.csv")
    summary2.to_csv("/content/outputs/scoring/summary_part2.csv")

    print("\nSummaries saved to /content/outputs/scoring/")


summarize_scores()

import shutil

# Create zip archive of all outputs
shutil.make_archive("/content/project_outputs", "zip", "/content/outputs")

print("Packaging completed. Download link:")

from google.colab import files
files.download("/content/project_outputs.zip")